# Generated by Django 4.1.2 on 2022-11-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateTimeField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("error", "error"), ("info", "info")], max_length=10
                    ),
                ),
                ("message_body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DoorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateTimeField()),
                (
                    "door_state",
                    models.CharField(
                        choices=[("opened", "opened"), ("closed", "closed")],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
