# Generated by Django 4.1.2 on 2022-11-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="message_type",
            field=models.CharField(
                choices=[("error", "ERROR"), ("info", "INFO")], max_length=10
            ),
        ),
    ]
