# Generated by Django 4.1.2 on 2022-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_main", "0002_alter_devicelog_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="message_type",
            field=models.CharField(
                choices=[("ERROR", "ERROR"), ("INFO", "INFO")], max_length=10
            ),
        ),
    ]
