# Generated by Django 4.1.2 on 2023-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('door_state', models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], max_length=6)),
            ],
        ),
    ]
